function IndividualResponseAndValueDifference = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  INDIVIDUALRESPONSEANDVALUEDIFFERENCE = IMPORTFILE1(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a string array.
%
%  INDIVIDUALRESPONSEANDVALUEDIFFERENCE = IMPORTFILE1(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  IndividualResponseAndValueDifference = importfile1("C:\Users\lcavalcantesie\Desktop\AiTech\20.Collaborations\Rijk\Paper - Ultimatum game and moral analyzer\GIT - Moral Ultimatum Game\moral-ultimatum-game\Matlab code - AA\IndividualResponseAndValueDifference.2019.Jul.03.10_24_48.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Jul-2019 14:17:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["run", "random_seed", "tick", "ID", "LastAction", "ValueDifference"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
IndividualResponseAndValueDifference = readtable(filename, opts);

%% Convert to output type
IndividualResponseAndValueDifference = table2array(IndividualResponseAndValueDifference);
IndividualResponseAndValueDifference = str2double(IndividualResponseAndValueDifference);
IndividualResponseAndValueDifference=table(IndividualResponseAndValueDifference(:,3),IndividualResponseAndValueDifference(:,4),IndividualResponseAndValueDifference(:,5),...
    IndividualResponseAndValueDifference(:,6),'VariableNames',["tick", "ID", "LastAction", "ValueDifference"]);

end